// Replace yourField with FieldName
const context = oEvent.oSource.getBindingContext();

// Get Entire Model
const data = context.getObject();

modelPageDetail.setData(data);

// debugger;

// GS_INCIDENTS = data;

// var options = {
//     parameters: {
//         "$select": "", // Optional 
//         "sap-client": "800" // Required 
//     },
//     data: {
//         GS_INCIDENTS
//     }
// };

// apiRestAPIGetIncidentPics(options);